FROM golang:1.7
RUN go get github.com/tools/godep
ADD . /go/src/github.com/iadvize/infra-demo
ADD https://get.docker.com/builds/Linux/x86_64/docker-1.13.0.tgz /usr/local/bin/docker
RUN chmod +x /usr/local/bin/docker
WORKDIR /go/src/github.com/iadvize/infra-demo
